/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    ExampleIcon: typeof import('./src/components/ExampleIcon.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ICarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    'IIconParkOutline:alignTextLeftOne': typeof import('~icons/icon-park-outline/align-text-left-one')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
