/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ICarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    'IIconParkOutline:alignTextLeftOne': typeof import('~icons/icon-park-outline/align-text-left-one')['default']
  }
}
